/* ---------Group Information---------
Group Number: 15

Yash Mundada: 2021A7PS0001P
Aaryan Garg: 2021A7PS2222P
Dev Kulkarni: 2021A7PS2430P
Radhey Kanade: 2021A7PS2534P
Shardul Shingare: 2021A7PS2539P
Shantanu Ambekar: 2021A7PS2540P
--------------------------------------*/

#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include "lexer.h"
#include "lexerDef.h"
#include "symbol_table.h"
#include "parser.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <time.h>

int main(int argc, char *argv[]) {
    while(1) {
        int option;
        printf("\n-----------MENU-----------\n");
        printf("Press 0 to exit\n");
        printf("Press 1 to remove comments\n");
        printf("Press 2 to print the token list generated by lexer\n");
        printf("Press 3 to print the parse tree along with errors\n");
        printf("Press 4 to print the total time taken\n");
        printf("--------------------------\n");
        printf("Enter your option: ");
        scanf("%d", &option);
        if (argc != 3) {
            printf("Invalid number of arguments : ./stage1exe {source file} {parsetree outfile}\n");
            break;
        }

        char *filename = argv[1];
        char *outfile = argv[2];
        clock_t start_time, end_time;
        double total_CPU_time, total_CPU_time_in_seconds;

        if (option == 0) {
            break;
        }
        else if (option == 1) {
            // remove comments
            removeComments(filename);
        }
        else if (option == 2) {
            // print token list
            lexer_main(filename);
            printf("\n");
        }
        else if (option == 3) {
            // print parse tree
            start_time = clock();

            parser_main(filename, outfile);
            printf("\n");

            end_time = clock();
            total_CPU_time = (double) (end_time - start_time);
            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
        }
        else if (option == 4) {
            // print time
            printf("\033[0;32m");
            printf("\nTotal CPU time: %f\n", total_CPU_time);
            printf("Total CPU time in seconds: %f\n", total_CPU_time_in_seconds);
            printf("\033[0m");
        }
        else {
            printf("Invalid option\n");
        }
    }
}