#include <stdio.h>
#include "lexer.h"
#include "lexerDef.h"
#include "symbol_table.h"
#include "parser.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

// --------**GLOBAL VARIABLES**--------
// int state = 0;
// int lexemeBegin,forwardPtr;
// int tokenSize=0;
// int lineNo=1;

// char buffer[2 * BUFFER_SIZE];
// FILE *filePointer;
// --------**GLOBAL VARIABLES**--------

int main(void) {
    while(1) {
        int option;
        printf("\n-----------MENU-----------\n");
        printf("Press 0 to exit\n");
        printf("Press 1 to remove comments\n");
        printf("Press 2 to print the token list generated by lexer\n");
        printf("Press 3 to print the parse tree along with errors\n");
        printf("Press 4 to print the total time taken\n");
        printf("--------------------------\n");
        printf("Enter your option: ");
        scanf("%d", &option);

        if (option == 0) {
            break;
        }
        else if (option == 1) {
            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);
            removeComments(filename);
        }
        else if (option == 2) {
            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);
            lexer_main(filename);
            printf("\n");
        }
        else if (option == 3) {
            // print parse tree
            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);
            parser_main(filename);
            printf("\n");
        }
        else if (option == 4) {
            // print total time taken
        }
        else {
            printf("Invalid option\n");
        }
    }
}