#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include "lexer.h"
#include "lexerDef.h"
#include "symbol_table.h"
#include "parser.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <time.h>

int main(void) {
    while(1) {
        int option;
        printf("\n-----------MENU-----------\n");
        printf("Press 0 to exit\n");
        printf("Press 1 to remove comments\n");
        printf("Press 2 to print the token list generated by lexer\n");
        printf("Press 3 to print the parse tree along with errors\n");
        printf("Press 4 to print the total time taken\n");
        printf("--------------------------\n");
        printf("Enter your option: ");
        scanf("%d", &option);

        if (option == 0) {
            break;
        }
        else if (option == 1) {
            // remove comments
            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);
            removeComments(filename);
        }
        else if (option == 2) {
            // print token list
            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);
            lexer_main(filename);
            printf("\n");
        }
        else if (option == 3) {
            // print parse tree
            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);
            parser_main(filename);
            printf("\n");
        }
        else if (option == 4) {
            // measure time
            clock_t start_time, end_time;
            double total_CPU_time, total_CPU_time_in_seconds;
            start_time = clock();

            char *filename = malloc(100 * sizeof(char));
            printf("Enter the filename: ");
            scanf("%s", filename);

            int original_stdout = dup(fileno(stdout));
            int devnull = open("/dev/null", O_WRONLY);

            dup2(devnull, fileno(stdout));
            lexer_main(filename);
            parser_main(filename);
            dup2(original_stdout, fileno(stdout));

            end_time = clock();
            total_CPU_time = (double) (end_time - start_time);
            total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
            printf("\033[0;32m");
            printf("\nTotal CPU time: %f\n", total_CPU_time);
            printf("Total CPU time in seconds: %f\n", total_CPU_time_in_seconds);
            printf("\033[0m");
        }
        else {
            printf("Invalid option\n");
        }
    }
}